"""add pin hash to users

Revision ID: 35a6bddd8d88
Revises: e9c1a14a13c2
Create Date: 2026-09-18 16:38:00.025662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a6bddd8d88'
down_revision: Union[str, Sequence[str], None] = 'e9c1a14a13c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin_hash')
    # ### end Alembic commands ###
